### ISSUE TITLE
[v0.02-Alpha] 输入一个特定正常方程式后程序卡死在计算界面

### ISSUE THREAD

**Issue by DuckSoft** [DuckSoft/GlockChem#20]
## Bug重现
Bug涉及的方程式很可能包括但不限于本例中的那个。
下例：
1. 打开程序，输入方程式：`KMnO4->K2MnO4+MnO2+O2`
2. 随意给定任意一个反应物一个正确的质量
3. 程序卡死在计算界面

## Bug现象
如图，白屏：
![image](https://user-images.githubusercontent.com/7822648/27752021-9064977a-5e11-11e7-9617-744f0127206c.png)

**Comment by DuckSoft** [comment]
这个 Issue 我看代码仔细分析了很长时间，还是没有找到原因。
或许在 IDE 下单步调试会有所帮助。

**Comment by DuckSoft** [comment]
在 Windows 下使用 `java -jar GlockChem-AWTUI.jar` 运行（启用控制台错误输出）后，重现问题时，控制台返回下列信息：
```
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at org.chembar.glockchem.ui.AwtUI.fin(AwtUI.java:132)
```
经过追溯，问题出现在`org.chembar.glockchem.ui.AwtUI.fin(AwtUI.java:132)`（点击[此处](https://github.com/DuckSoft/GlockChem/blob/47942fd08789671516bfdc9cf8fa7f64147af0a7/src/org/chembar/glockchem/ui/AwtUI.java#L132)打开）的一行代码上：
```java
EquationConditionMass condition = new EquationConditionMass(equation.reactant.get(1), new AdvNum(numCondition));
```
注意到`equation.reactant.get(1)`方法中的1对应反应物数组中的**第二个元素**，而我们上面使用的引发 Bug 的例子`KMnO4->K2MnO4+MnO2+O2`中**只有一个反应物**，因而引发了`java.util.ArrayList.rangeCheck`的`java.lang.IndexOutOfBoundsException`异常。

供参考。
